[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[env]
# Follow https://unix.stackexchange.com/a/678901 to setup alacritty and test using infocmp
TERM = "alacritty"

[window]
decorations = "Buttonless"
padding = {x =  10, y = 10}
startup_mode = "Maximized"
option_as_alt = "Both"

[colors.primary]
background = "#222222"

[font]
size = 13.0
